### ISSUE TITLE
recommended IDs to add

### ISSUE THREAD

**Issue by activeworld** [hyperbrew/after-effects-command-ids#5]
I am new to github so i apologize if there are better ways to submit updates... i am still learning. here are a few more IDs that are missing (found here: https://www.provideocoalition.com/wp-content/uploads/AECC2015_MenuIDs_v1_0_1-1.pdf):

Scripts = 8100
Run Script File... = 8000
Open Script Editor = 8001
script1.jsx = 8101
script2.jsx = 8102
script3.jsx = 8103
script4.jsx = 8104
script5.jsx = 8105
script6.jsx = 8106
script7.jsx = 8107
script8.jsx = 8108
script9.jsx = 8109
script10.jsx = 8110
(and so on for additional scripts)

Cancel Caching Work Area in Background = 3985
Preview > Audio = 7001
Save Frame As > Photoshop Layers...= 5001

Layer Styles
> Drop Shadow = 9000
> Inner Shadow = 9001
> Outer Glow = 9002
> Inner Glow = 9003
> Bevel and Emboss = 9004
> Satin = 9005
> Color Overlay = 9006
> Gradient Overlay = 9007
> Stroke= 9008

Track in Mocha = 5007 (adds effect to layer, but does not open Mocha)

**Comment by justintaylor-dev** [comment]
Thanks for the suggestion. I've added a new "manual" list of entries submitted like this.

Added all except:
- Open Script Editor = 8001 - I don't think this is relevant anymore since ESTK is deprecated.
- Preview > Audio = 7001 - doesn't appear to work

Changes:
- 5001 is now Progress Panel
- 5001 is now Mocha
